sudo: required

language: java

env:
  - APP_NAME=
  - AWS_ECR_ACCOUNT=

services:
  - docker

script:
  - mvn clean package

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-east-1)
  - docker build -t $APP_NAME:latest .
  - docker tag $APP_NAME:$TRAVIS_BUILD_ID $AWS_ECR_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:latest
  - docker push $AWS_ECR_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:latest