spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/playapi
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/liquibase-changelog.xml

server:
  port: 8080

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
security.basic.enabled: false
management.security.enabled: false

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE

#spring.jpa.properties.hibernate.physical_naming_strategy: com.tcreeds.play.config.FunctionalNaming
#spring.jpa.properties.hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

#spring.jpa.hibernate.naming.implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

#spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl