spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/playapi
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/liquibase-changelog.xml

server:
  port: 8080

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
security.basic.enabled: false
management.security.enabled: false